---
- hosts: bottleserver
  remote_user: ec2-user
  become: true
  tasks:
    - name: test connection
      ping:
    - name: create bottle directory
      file:
        path: /tmp/bottle
        state: directory
        mode: 0755
    - name: Copy hello.py to client
      copy: src=~/hello.py dest=/tmp/bottle/hello.py
    - name: install bottle
      command: pip install bottle
      become_method: sudo
    - name : install cherrypy
      command: pip install "cherrypy>=3.8.0,<9.0.0"