---
- hosts: bottleserver
  remote_user: ec2-user
  become: yes
  tasks:
    - name: test connection
      ping:
    - file:
      path: /tmp/bottle
      state: directory
      mode: 0755
    - name: Copy hello.py to client
      copy: src=~/hello.py dest=/tmp/bottle/hello.py
    - name: install bottle
      command: sudo pip install bottle
    - name: Start bottle
      command: python /tmp/bottle/hello.py