AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket
Parameters:
  BucketName:
    Description: Name of the S3 bucket must be unique in the region
    Type: String
  ProjectTag:
    Description: Tag value for the project
    Type: String
  
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      AccessControl: String
      BucketName: !Ref BucketName 
      Tags:
        -
          Key: Project
          Value: !Ref ProjectTag

Outputs:
  DomainName:
    Value: !GetAtt
      - Bucket
      - DomainName
    Description: DomainName of the bucket