AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket given the owner full control.
Parameters:
  BucketName:
    Description: Name of the S3 bucket must be globally unique and can contain lowercase characters, numbers and hyphens
    Type: String
  ProjectTag:
    Description: Tag value for the project
    Type: String
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref BucketName 
      Tags:
        -
          Key: Project
          Value: !Ref ProjectTag
Outputs:
  DomainName:
    Value: !GetAtt
      - Bucket
      - DomainName
    Description: DomainName of the bucket